spring.application.name=spring-boot-project
spring.datasource.url=jdbc:postgresql://localhost:5432/stockpilot
spring.datasource.username=postgres
spring.datasource.password=postgres
march.folder=C:\Users\ME-PC\.march\spring-boot-project